var $ = require('./jquery.min.js');
window.jQuery = $;
window.$ = $;
require('./jquery.bookblock.js');
require('./particles.min.js');
var smoothScroll = require('./smoothscroll.min.js');
window.smoothScroll = smoothScroll;
require('./swiper.jquery.min.js');
var Handlebars = require('./handlebars.min.js');
window.smoothScroll = Handlebars;